monzo/docs

source/includes/_feed_items.md

Fix feed item example image

---

source/includes/_attachments.md
source/index.md

Think this is about right :wink: 
- Upload attachments
- Register attachments
- Deregister attachments

Document image attachment API

---

source/includes/_accounts.md
source/index.md

Add documentation for accounts API

---

source/includes/_transactions.md

Document emoji and other transaction flags

---

source/includes/_balance.md
source/index.md

Document balance API

---

source/includes/_transactions.md
source/includes/_web_hooks.md

Please deploy after merging using `rake publish`. Need to do `bundle install` first

Add all fields to docs

---

source/includes/_accounts.md
source/includes/_attachments.md
source/includes/_authentication.md
source/includes/_balance.md
source/includes/_feed_items.md
source/includes/_transactions.md
source/includes/_web_hooks.md
source/index.md

`s/production-api.gmon.io/api.getmondo.co.uk`

Update API urls

---

source/includes/_authentication.md
source/index.md

Document OAuth 2.0 Authorization Code Grant

---

source/includes/_webhooks.md
source/index.md
source/layouts/layout.erb

Extremely minor tweaks to webhook wording

---

source/includes/_authentication.md

Fix typo in URL

---

source/includes/_feed_items.md

Useful to know for testing on your own account (you don't want to end up with a bunch of test feed items clogging up your app).

Feed items dismissable

---

source/index.md

Switch two words

---

source/layouts/layout.erb

Noticed this as Slack displays the `og:description` ;)

Fix stray Mondos

---

CONTRIBUTING.md
source/includes/_accounts.md

How do we actually build this? is merging into master enough or is there an additional step?

explain how to access current accounts

---

source/includes/_balance.md
source/includes/_pots.md
source/index.md

document pots API

---

source/includes/_ais.md
source/index.md

Mostly because the horizontal rule formatting was bugging me. 🐛

Small cleanup of AIS section

---

source/includes/_cbpii.md
source/includes/_pis.md
source/index.md

`Publish the technical specification for our dedicated interface (this is a set of tools, protocols and routines needed by TPP to connect with us)`
https://monzo.slack.com/archives/C04SGGS1S/p1552397872101100?thread_ts=1552390074.098100&cid=C04SGGS1S

PSD2 changes

---

source/includes/_feed_items.md

https://developer.android.com/reference/android/graphics/Color.html#parseColor(java.lang.String)

Make it very clear the colours must be #RRGGBB

---

Dockerfile
source/includes/_ais.md
source/includes/_cbpii.md
source/includes/_pis.md
source/index.md

- Adds new AIS documentation
- Adds new PIS documentation
- Adds new CBPII documentation
- Updates the Dockerfile so that the project may be built locally in Docker

Update AIS, PIS, CBPII docs

---

source/includes/_ais.md
source/includes/_cbpii.md
source/includes/_pis.md
source/index.md

We'll be replacing this with the Parties endpoint.

[Open Banking] Remove customer endpoint, add base URLs

---

source/includes/_ais.md
source/includes/_pis.md

We often have third parties ask us for this information, so might as well document these test users they can use :)

Open Banking:Add Sandbox users to the docs

---

source/includes/_ais.md

This PR updates the documentation for the Parties AIS data now that we support the account/{...}/party and parties endpoints.

Add new party endpoints to AIS documentation

---

source/includes/_ais.md
source/includes/_cbpii.md
source/includes/_pis.md

Just to be more helpful in case people miss the sections above.

Add a link to the .well-known endpoints section from dynamic client reg

---

source/includes/_ais.md
source/includes/_cbpii.md
source/includes/_pis.md

**OBIE v3.1.5 Upgrade**
- `Debtor/Name`
- `TransactionMutability`

OBIE v3.1.5 Upgrade

---

source/includes/_ais.md
source/includes/_cbpii.md
source/includes/_pis.md

Publish OBIE v3.1.7 & v3.1.8 changes to Monzo API Docs

v3.1.7 & v3.1.8

---

source/includes/_scarts.md
source/index.html.md

SCA-RTS (PS21/19) documentation update

SCA-RTS docs

---

source/includes/_ais.md

Adds information about the `ProprietaryBankTransactionCode` field both the `Issuer` & `Code` properties

Adds ProprietaryBankTransactionCode information

---

source/includes/_ais.md

Adds a line break to fix the parties header

Fix parties heading

---

source/includes/_ais.md
source/includes/_pis.md

* document that there are different company types for business account and how API shows it
* document default limits for account types

OB:  update docs on account limits and business company types

---

source/includes/_vrp.md
source/index.html.md

Add documentation for Open Banking Variable Recurring Payments API

Vrp sweeping api

---

source/includes/_ais.md

Adds new flex balances section

---

source/includes/_ais.md

Adds flex to the list of account types for AIS API

---

source/includes/_pots.md

Add a note about using the pot withdrawal API with pots which have been protected with added security.

Document added security for pot withdrawals

---

source/includes/_ob_errors.md

Adds error section about rate limiting
