monzo/docs

source/includes/_authentication.md
`s/getmondo.uk/getmondo.co.uk/`
=> Fix typo in oauth redirect url

source/includes/_authentication.md
This changes the link into an HTML link so that it's rendered correctly.
Fixes #33
=> Change markdown link to HTML link

source/includes/_transactions.md
Without the `--form` option the request body is sent json-encoded, which the API doesn't support.
=> Use form encoding in transaction annotation call

source/includes/_transactions.md
This fixes some typos in the docs for transactions, where the "settled" field has values of type bool when they should really be dates instead.
=> Fixed "settled" fields in JSON responses to be dates, not bools

source/includes/_transactions.md
Someone noticed the HTTPie example for listing transactions returns `Method not allowed`, turns out HTTPie defaults to `POST` if params are passed with a single `=`.
This changes the examples to use query string params where appropriate, and `==` elsewhere.
Shout-out to @domwong  for his HTTPie knowledge
=> Correct examples where GET requests incorrectly execute as POST

source/index.md
Minor change: <code>OS X</code> is now called <code>macOS</code>
=> OS X -> macOS

source/index.md
Changes the link to use devslack.monzo.com
=> CORE-301_change_devslack_to_monzo

source/includes/_ais.md
Adds /ais/pots to the documented ais endpoint
=> add listing pots to the documented ais api

source/includes/_balance.md
There has been a bit of confusion in the API Slack channel about the different values and what they marry up to be.
Given James' answer here: https://monzodevelopers.slack.com/archives/C0KP3SB29/p1513949338000264?thread_ts=1513944878000244&cid=C0KP3SB29 - Thought I'd add it to the actual docs to help with the next guy coming along!
=> Add information about `total_balance` value

source/includes/_webhooks.md
Since `settled` is not a boolean parameter but a nullable datetime
=> Update `settled` parameter in transaction webhook

source/includes/_transactions.md
I suspect there might be more values missing from this list. What about invalid expiry date and invalid PIN?
=> Updated list of `decline_reason` values

source/index.md
We've retired the Developers Slack now. 
This is to update the note on the home page to point people to the Developers forum category instead.
=> Swapping DevSlack link for forum category

source/includes/_receipts.md
As advised by kieranmch at https://community.monzo.com/t/monzo-receipt-api-issues/59518
it is correct behaviour of the API that nothing is returned.
=> Fix documentation error on creating receipt. closes #99

source/includes/_ais.md, source/includes/_cbpii.md, source/includes/_pis.md
I've kept the Getting Access section as it's the most-likely question people will ask, and they may not necessarily have the patience to read down to `Dynamic Client Registration`. 
I've also shunted our email address all the way to the bottom, it _may_ help reduce inbound and promote self-service
=> Add dynamic client registration info

source/includes/_attachments.md
This PR adds documentation for the fact that the `content_length` parameter on the attachment API is now mandatory.
=> Document that the content_length parameter on the attachment API is now mandatory.

source/includes/_pots.md
This is now a required parameter, previously it would default to the `uk_retail` if not specified.
=> Document GET /pots current_account_id param

source/includes/_transactions.md
We haven't stored a balance snapshot against transactions for years, we should stop referring to it in our API docs
=> [MNZ-629] Remove references to account_balance on transactions API

source/includes/_ais.md, source/includes/_cbpii.md, source/includes/_pis.md
Now that the changes for SCA-RTS PS21/19 are live the docs can be updated to reflect v3.1.10
=> publish `v3.1.10` now SCA-RTS changes are live

source/includes/_pis.md
Update Payment Initiation Services API - Domestic payment docs on redirection error returned in case of insufficient funds.
=> OB:  update PIS documentation about error returned in case of insufficient funds

source/includes/_vrp.md
a TPP pointed out our testing documentation isn't correct for VRPs with regard to `DesiredStatus`
=> correct testing docs for VRP

source/index.html.md
The blog post mentioned in this text has been deleted and the link goes to a 404.
=> Remove link to deleted blog post

source/includes/_eu.md
This PR updates Open Banking documentation on CBPII API for EU.
=> Open Banking EU: update CBPII docs section

source/layouts/layout.erb
Remove Google Analytics Universal Analytics.
[Google analytics UA](https://support.google.com/analytics/answer/11583528?hl=en) was sunsetted on July 1, 2024.
=> Remove google analytics UA from layout
